name: Vol Edge QR Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy-qr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Inject QR
        run: |
          echo -e '\n<div align="center"><a href="https://linktr.ee/koripickle" target="_blank"><img src="vol-edge-qr-code.jpg" width="200" style="border: 2px solid rgb(255, 130, 0);"></a><p>Vol Edge RCM Suite</p></div>' >> README.md
      - name: Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Hardcore Automation Trigger" || exit 0
          git push
